# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=24)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('last_updated', models.DateTimeField(null=True)),
                ('imo', models.IntegerField(null=True)),
                ('ais_class', models.CharField(max_length=1, null=True)),
                ('flag', models.CharField(max_length=12)),
                ('nationality', models.CharField(max_length=255)),
                ('tonnage', models.FloatField(null=True)),
                ('draught', models.FloatField(null=True)),
                ('ship_type', models.IntegerField(null=True)),
                ('mmsi_type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('fill_bits', models.IntegerField()),
                ('decode_error', models.BooleanField(default=False)),
                ('time_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rawreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='harbormaster.RawReport')),
                ('report_type', models.IntegerField()),
                ('decoded', django.contrib.postgres.fields.jsonb.JSONField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harbormaster.Contact')),
            ],
            bases=('harbormaster.rawreport',),
        ),
        migrations.AddField(
            model_name='rawreport',
            name='collection_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='harbormaster.CollectionLabel'),
        ),
    ]
