# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harbormaster', '0002_auto_20160814_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_sighting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
