# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbormaster', '0003_contact_first_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='draught',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
