# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbormaster', '0004_auto_20160819_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_sighting',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mmsi',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='rawreport',
            name='time_received',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.IntegerField(db_index=True),
        ),
    ]
