# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harbormaster', '0005_auto_20160823_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_updated',
            new_name='last_sighting',
        ),
    ]
