# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbormaster', '0006_auto_20160823_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='callsign',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='dim_to_bow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='dim_to_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='dim_to_starboard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='dim_to_stern',
            field=models.IntegerField(null=True),
        ),
    ]
