# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbormaster', '0008_auto_20160824_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latest_heading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='latest_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='latest_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='latest_navigation_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='latest_speed',
            field=models.FloatField(null=True),
        ),
    ]
